# Site settings
title: Coded Thoughts
email: csaden@gmail.com
description: "Learn, think, code."
baseurl: # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ChrisSaden
github_username: csaden
linkedin_username: ChrisSaden
pages:
 - title: About
   url: /about
 - title: HackReactor
   url: /hackreactor
 - title: Javascript
   url: /javascript
 - title: Archive
   url: /archive

# Build settings
markdown: kramdown
permalink: none
highlighter: pygments
paginate: 10
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]