# Site settings
title: Code-Ed Thoughts
email: csaden@gmail.com
description: "Learn, think, code."
baseurl: # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ChrisSaden
github_username: csaden
pages:
  About: '/about'
  HackReactor: '/HackReactor'
  Feed: '/atom.xml'

# Build settings
markdown: kramdown
permalink: pretty
pygments: true
paginate: 10
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]